### ISSUE TITLE
python_version returns 3.10 which is interpreted as 3.5

### ISSUE THREAD

**Issue by tirkarthi** [numat/productivity#32]
A better way to check is to compare `sys.version_info < (3, 5)` . Fedora bug : https://bugzilla.redhat.com/show_bug.cgi?id=1900697

```
~/cpython/python
Python 3.10.0a5+ (heads/master:cd80f430da, Feb 17 2021, 14:08:19) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from platform import python_version
>>> python_version()
'3.10.0a5+'
>>> python_version() < '3.5'
True
```

https://github.com/numat/productivity/blob/f25d1070df2c738c13ecca65137493eb4c164f27/setup.py#L5

**Comment by JamesJeffryes** [comment]
Thanks for the heads up! This is actually one of those broken clocks being right twice a day because this library will actually not be compatible with >3.10 until `pymodbus` is updated but I'll change it to fail for the right reasons.
