### ISSUE TITLE
Identify and fix root cause of failure to read >125 registers

### ISSUE THREAD

**Issue by alexrudd2** [numat/productivity#38]
See PR #37 

`clickplc` should NOT be affected, per Pat's prior testing.

Check with `huber` and `midas`, which share code.

I plan to setup a test PLC with static data to troubleshoot more easily.

**Comment by alexrudd2** [comment]
[plc_tags_basic.csv](https://github.com/numat/productivity/files/7108570/plc_tags_basic.csv)

`192.168.10.107`

**Comment by alexrudd2** [comment]
The patch from 125 to 124 fixes my two physical PLCs with real data, but breaks things on a physical PLC with simulated data. 

patched
```
    "test36": 123,
    "test37": 125,
    "test38": 125,  // should be 127
    "test39": 127 // should be 129
```

Still it gives me a clue as to what's going wrong.  `decoder._pointer` somehow has a mismatch of 2 bytes from the data, at addresses `400126` or higher - that is, addresses on the second read.  I'm not sure if the problem is the pointer or the data.  Both PLCs have a 19-character string `sys4_vac_status` starting at `400126` and ending at `400135`.  With the unpatched code you can see two junk characters at the start.
``` 
"sys4_vac_status": ",\u00c2047A;0500;0000;00",
                       ^^^^
```
The "fix" for the live PLCs duplicates the values for `400125` into `400126`, essentially undoing the 2-byte mismatch.  Unfortunately I can't replicate the problem on my test PLC, even with a 19-character string at `400126`!!  It must be one of the earlier registers that's triggering the problem.  I suspect the 32-bit int immediately preceding, from `400124` to `400125`.

**Comment by alexrudd2** [comment]
[plc_tags_basic.csv](https://github.com/numat/productivity/files/7124619/plc_tags_basic.csv) matches the live PLC at `192.168.10.107`

**Comment by patrickfuller** [comment]
Sounds like there's fun python debugging in your future!

What happens if you request the registers one at a time and stitch it all together? If that works, what about 2 at a time? Etc.

Similar - maybe the option is to limit reading to 60 registers (120 bytes). Below the modbus standard but you can be sure there's no 124 vs 125 issue there and performance loss is minimal.

**Comment by alexrudd2** [comment]
This has got to be one of the most annoying things I've ever debugged.   Here's the answer:

<img width="331" alt="Screen Shot 2021-09-08 at 6 22 52 PM" src="https://user-images.githubusercontent.com/52292902/132598210-c952c381-3df7-48c5-8fc4-8a827861479c.png">
The default is checked.


If you request a 32bit tag, _it's mapped across two 16bit modbus registers_.  
(1) If you're requesting a batch of tags all at once, that's fine - they arrive swapped and the `BinaryPayloadDecoder` uses little-endian byte order to decode them correctly.  
(2)If you request multiple batches of tags, and the boundary between batches falls on a 16bit tag**, or in the middle of a string, or on the edge of a 32bit tag, that's fine because all the 32bit tags arrive swapped and they decode properly.
(3)If you request multiple batches, and the boundary _falls right in the middle_ of a 32bit tag, bad things happen.
**(the driver doesn't read these, but I "cleverly" used them for debugging)

Here, I have 3 consecutive 32bit tags across addresses `124/125`, `126/127`, and  `128/129` 
<img width="416" alt="Screen Shot 2021-09-08 at 6 57 37 PM" src="https://user-images.githubusercontent.com/52292902/132600808-dfb96fb9-a5cd-4627-8b6b-f22df32e92bf.png">. 
The first tag has a value of `(2^16)*125+124`, the second `(2^16)*127+126`, etc.  This means, with little endian encoding (i.e. swap box checked), each 16bit register will have a value corresponding to its address.  The driver reads 125 addresses (case 2)
`[...124, 125] + [126, 127, 128, 129]`
Everything is fine.

Now, say I read 124 addresses (case 3).
`[...124]+[125, 126, 129, 126, 0]`
The reply is garbled junk.  123 addresses works perfectly fine, 121 is garbage.  125 was a [magic number](https://github.com/numat/productivity/pull/37) for the two PLCs I cared about that happened to have a tag split right across `124/125`, but would break any PLC with a tag split across `125/126`!

**Comment by alexrudd2** [comment]
Workarounds:
1.  Switch the driver's `BinaryPayloadDecoder` to be `wordorder=Endian.Big` and uncheck the box for every existing and new Productivity PLC.
2. Make sure never to split 32-bit tags across the static maximum number of tags read.
3. Parse the tags file first to determine a dynamic maximum number of tags to read.
4. Figure out in exactly which way the response is mangled, and attempt to un-mangle it.
5. Ask AutomationDirect if this is intended behavior; hope for a firmware upgrade to consistently swap regardless of request boundaries.
6. Don't ever use more than 124 tags, or if you do accept a 50/50 chance of the later ones being screwed up.
7. F^&$!@ this, it's time for a beer.

**Comment by alexrudd2** [comment]
<img width="537" alt="Screen Shot 2021-09-08 at 7 20 47 PM" src="https://user-images.githubusercontent.com/52292902/132602432-73f83bcb-8996-47de-9f32-582cc4d77757.png">
Topic P198 in the [P2000 help files](https://www.automationdirect.com/productivity/software/help/)

**Comment by JamesJeffryes** [comment]
🍻  Well done!

> Switch the driver's BinaryPayloadDecoder to be wordorder=Endian.Big and uncheck the box for every existing and new Productivity PLC.

I don't think we can feasibly switch the word order for all existing and new productivity PLCs as well expect anyone using the driver to do the same (even if we say this is a beta driver).

> Make sure never to split 32-bit tags across the static maximum number of tags read.
> Parse the tags file first to determine a dynamic maximum number of tags to read.
> Figure out in exactly which way the response is mangled, and attempt to un-mangle it.

This should be doable but there's probably more edge cases to be discovered. I might need your help thinking though how strings are represented.

> Ask AutomationDirect if this is intended behavior; hope for a firmware upgrade to consistently swap regardless of request boundaries.

I think we should definitely ask AD about the behavior as it seems problematic but I'm not sure that they will fix quickly.

> Don't ever use more than 124 tags, or if you do accept a 50/50 chance of the later ones being screwed up.

Not a long term solution but would actually work for most of our existing controllers. IIRC the over long ones have gaps in their modbus addresses and could be packed below the read limit, alternatively, we could just introduce a gap where needed to make sure that any extra tags start on a compatable address

**Comment by patrickfuller** [comment]
@alexrudd2 I want to make sure I'm understanding what the bug is and say it simply. The default register order is little endian, so if you have a 2-register float and only request the first register, you will actually get the second register back. Is this right? Also, if you request the second register, do you get the first one?

> I don't think we can feasibly switch the word order for all existing and new productivity PLCs as well expect anyone using the driver to do the same (even if we say this is a beta driver).

100% agreed. The goal of these drivers is to provide an abstraction and custom config breaks that.

> This should be doable but there's probably more edge cases to be discovered. I might need your help thinking though how strings are represented.

I haven't read the source in a while, but my view on how it works is 1. read and cache all addresses, 2. stitch, 3. parse all. If that's the case, I don't know how this is happening? Maybe my understanding above is wrong.

My fix recommendation would be in the python layer, as keeping the "it just works" feeling of the driver is important. We could cross-reference the tags file with the modbus requests, breaking requests by whatever tag ends closest to 124 bytes without going over (maybe except strings). We can skip this check if <124 bytes so it's unobtrusive to the common use case. Thoughts?

**Comment by alexrudd2** [comment]
>> I don't think we can feasibly switch the word order for all existing and new productivity PLCs as well expect anyone using the driver to do the same (even if we say this is a beta driver).

> 100% agreed. The goal of these drivers is to provide an abstraction and custom config breaks that.

Agreed, just listing it for completeness.

> alternatively, we could just introduce a gap where needed to make sure that any extra tags start on a compatible address

CI could catch this I suppose.   Not thrilled at the bandaid, though.

> The default register order is little endian, so if you have a 2-register float and only request the first register, you will actually get the second register back. Is this right? Also, if you request the second register, do you get the first one?

This is true for 2-register ints and floats**; strings are unaffected.  It appears that if you request the first register at the end of a group, you get it back.  If you request the second register at the beginning of a group, you get it back, but the rest of reply is shifted/mangled.  I'm not sure what happens if you read just the second register alone.

**(Consecutive bytes are big-endian in the spec, and MODICON went big-endian when they added 32-bit registers to their PLCs, but they didn't update the spec.  :(  Other vendors went little-endian, presumably for Intel chips in the 80s)

> We could cross-reference the tags file with the modbus requests, breaking requests by whatever tag ends closest to 124 bytes without going over (maybe except strings).

This (after contacting AD) is my intended solution, since I think we only ever need two options - strings are irrelevant.  **Default to 125, but read 124 if it would split a 32-bit register.**

**Comment by patrickfuller** [comment]
> Default to 125, but read 124 if it would split a 32-bit register. 

:100:
